// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhnEN9SWSJ2BbRxpvGY1Ia549VuzSffRM',
    appId: '1:14620606519:android:0d1a89ba527a8e3f1b7fb2',
    messagingSenderId: '14620606519',
    projectId: 'nsp2026',
    storageBucket: 'nsp2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpRjrChdBLPLMQ8Bsq0ZjafLMOzft7xkU',
    appId: '1:14620606519:ios:8d89aed2a2d51b7a1b7fb2',
    messagingSenderId: '14620606519',
    projectId: 'nsp2026',
    storageBucket: 'nsp2026.firebasestorage.app',
    iosBundleId: 'com.starwish.nsp2026',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1jqQCFj6qC4Snda6IHgizNSKV1hX1slQ',
    appId: '1:14620606519:web:13891d7b87de7b191b7fb2',
    messagingSenderId: '14620606519',
    projectId: 'nsp2026',
    authDomain: 'nsp2026.firebaseapp.com',
    storageBucket: 'nsp2026.firebasestorage.app',
    measurementId: 'G-J64XXQ1NGZ',
  );

}